apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-stg
  annotations:
    codefresh.io/product: worker
spec:
  project: default
  source:
    repoURL: https://github.com/CentricCodefreshPOC/codefresh-configs.git
    targetRevision: HEAD
    path: environments/staging/worker
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
