apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-prod
  annotations:
    codefresh.io/product: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/CentricCodefreshPOC/codefresh-configs.git
    targetRevision: HEAD
    path: environments/production/infrastructure
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
